from bs4 import BeautifulSoup as sop
from concurrent.futures import ThreadPoolExecutor as tred
import os,sys,time,json,random,re,string,platform,base64,platform,uuid
import requests,random,sys,json,os,re
from time import sleep
from os import system
import os,sys,time,datetime,random,hashlib,re,threading,json,urllib,uuid,ipaddress,calendar,requests,mechanize,bs4,sys,os,subprocess,uuid,requests,sys,random,time,re,base64,json,platform
import marshal
import zlib
import base64
from datetime import date
from datetime import datetime
from time import sleep
from time import sleep as waktu
from random import random as acak
from random import choice as pilih
from random import randint
from bs4 import BeautifulSoup
import requests as ress
from sys import exit as exit
###----------[ IMPORT LIBRARY ]---------- ###
import requests
import bs4
import sys
import os
import random
import time
import re
import json
import uuid
import subprocess
import marshal
import rich
import shutil
import webbrowser
from random import randint
from concurrent.futures import ThreadPoolExecutor as ThreadPool
from bs4 import BeautifulSoup as par
from datetime import date
from datetime import datetime
# from rich import print as printer
from datetime import date
import marshal
try:
    import requests
    from concurrent.futures import ThreadPoolExecutor as ThreadPool
    import mechanize
    from requests.exceptions import ConnectionError
except ModuleNotFoundError:
       print('\n Installing missing modules ...')
       os.system('pip install requests futures==2 > /dev/null')
       os.system('python Random.py')
from bs4 import BeautifulSoup
from datetime import date
from datetime import datetime
from time import sleep
NOVA ="""
\033[1;97m─────────────────────────────────────────────────────
  
\033[0;31m███    ██  ██████       █████  ██    ██  █████  ██ ██       █████  ██████  ██      ███████ 
\033[0;31m████   ██ ██    ██     ██   ██ ██    ██ ██   ██ ██ ██      ██   ██ ██   ██ ██      ██      
\033[0;31m██ ██  ██ ██    ██     ███████ ██    ██ ███████ ██ ██      ███████ ██████  ██      █████   
\033[0;31m██  ██ ██ ██    ██     ██   ██  ██  ██  ██   ██ ██ ██      ██   ██ ██   ██ ██      ██      
\033[0;31m██   ████  ██████      ██   ██   ████   ██   ██ ██ ███████ ██   ██ ██████  ███████ ███████ 
                                                                                           
                                                                                                                               
\033[1;97m─────────────────────────────────────────────────────"""
print(NOVA)